version: '{build}'
image:
  - Ubuntu
build_script:
  - ./mvnw clean package -DskipTests
test_script:
  - ./mvnw clean verify
#after_test:
#  - sh: CODECOV_TOKEN="0445262f-e25d-4081-8373-b9b2f14283f5" bash <(curl -s https://codecov.io/bash)
