version: '{build}'
image:
  - Ubuntu
build_script:
  - ./mvnw clean package -DskipTests
test_script:
  - ./mvnw clean verify
after_test:
  - sh: CODECOV_TOKEN='85cad102-62e2-421d-b432-55a5cbdfebfa' bash <(curl -s https://codecov.io/bash)
